### ISSUE TITLE
Proxy network commands

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/dev-proxy#148]
Raised from #49

The setup of the developer proxy is different depending on the operating system you use. 

- **On Windows**, the proxy is auto registered and un-registered as a system wide proxy. 
- **On macOS and Linux**, the proxy requires manual configuration on the a network device. 

This is not a consistent approach.

We should introduce commands in the proxy to reduce setup effort and be consistent.

1. **Setup and enable proxy on given network device**, `msgraph-developer-proxy network init --device <identifier>`
2. **Disable proxy on a given network device**, `msgraph-developer-proxy network disable --device <identifier>`
3. **Enable proxy on a given network device**, `msgraph-developer-proxy network enable --device <identifier>`

Introducing commands will simplify our documentation. All users, irrespective of their operating system, can use the same approach.

**Comment by waldekmastykarz** [comment]
A couple of questions:

- what does "setup" include?
- how would users know their device identifier?
- could we simplify to: `proxy register` and `proxy unregister` to attach the proxy to all currently enabled networks? If you have multiple networks enabled and we attach it only to one, wouldn't it be a hit and miss how the traffic is routed and whether it'll hit the proxy or not? Also, how would users know their device identifier? Isn't this adding an unnecessary complexity?
- I suggest we separate init from enable, because init is one-time

**Comment by garrytrinder** [comment]
I should have stated that the spec is heavily influenced by the way that the `networksetup` tool works on macOS.

> * what does "setup" include?
>
> * I suggest we separate init from enable, because init is one-time

Setup includes setting the domain and port values on the `Secure Web Proxy (HTTPS)`. The tool automatically enables the proxy when you set the values. We could disable the proxy after setting the values so it turns into just a setup command.

> * how would users know their device identifier?

The `networksetup` tool can return a list of network devices, this is a friendly name rather than an ID, so maybe name would be more appropriate for the option.

> * could we simplify to: `proxy register` and `proxy unregister`


Not sure if that would work cross OS, I'm not sure its possible to set a system wide proxy on macOS, from what I've seen you can only set it on a device basis. 


> If you have multiple networks enabled and we attach it only to one, wouldn't it be a hit and miss how the traffic is routed and whether it'll hit the proxy or not?

This might not be easy to do. For example, here is the list of devices I have on my machine that are enabled

Targus USB3 DV4K DOCK w PD60W
USB 10/100/1000 LAN
Wi-Fi
iPhone USB
Thunderbolt Bridge

I only use Wi-Fi but more are returned by the `networksetup` tool as being enabled when they are not active.

**Comment by waldekmastykarz** [comment]
Since Developer Proxy is cross-platform, let's consider how users on different OSes would look at our commands and options. Also, I've been using macOS for quite a few years, but have never used the `networksetup` tool for example, so let's not assume that it's common knowledge for our users.

> Not sure if that would work cross OS, I'm not sure its possible to set a system wide proxy on macOS, from what I've seen you can only set it on a device basis.

That's something we need to find out, because ideally we should have one way that works for everyone.

> I only use Wi-Fi but more are returned by the networksetup tool as being enabled when they are not active.

It would be interesting to learn how macOS chooses which network to use to route the traffic and if you're applying the proxy to only one of them, how sure you can be that the traffic will actually go through the proxy and not through one of the other available interfaces.

**Comment by waldekmastykarz** [comment]
I think #429 is a more convenient solution than providing a set of commands that folks need to run themselves.
