### ISSUE TITLE
For Windows setup this page is missing info about the need to run Microsoft.PowerShell_profile.ps1 after installing devproxy

### ISSUE THREAD

**Issue by Adam-it** [microsoft/dev-proxy#467]
### Type of issue

Missing information

### Feedback

IMO I would say we are missing information that after running the `(Invoke-WebRequest https://aka.ms/devproxy/setup.ps1).Content | Invoke-Expression` we should then run `Microsoft.PowerShell_profile.ps1` before we may start using the `devproxy` alias. Without that it won't work, so if someone goes over the  docs and immediately after running the step described in the 'Install' chapter and then starts going over 'Start Dev Proxy' step, then he or she will get an error in the first step as the `devproxy` is not recognized.
I know seems stupid but believe me it may happen 😅. I know that from ...ech... experience 🤣😊

anyway I say it's minor as the console guides you which is awesome 🤩
![image](https://github.com/microsoft/dev-proxy/assets/58668583/18d6908d-e59c-4ca0-a73c-227aea7ffc43)

but still it could be mentioned in the docs

### Page URL

https://learn.microsoft.com/en-us/microsoft-cloud/dev/dev-proxy/get-started?tabs=powershell%2Cpwsh&pivots=client-operating-system-windows

### Content source URL

https://github.com/MicrosoftDocs/microsoft-cloud/blob/main/docs/dev/dev-proxy/get-started.md

### Author

@garrytrinder

### Document Id

9b3459ea-8df0-e888-794d-6b0aba5f337a

**Comment by garrytrinder** [comment]
Thanks for the feedback @Adam-it.

Not including the dot sourcing of the profile file in the docs is intentional. As you've stated we show this step in the console window when you run the initial script but I can see how it could be missed if you are following the guide to the letter.

We have a few options and we could do both

1. Make the dot sourcing step in the console output more visible.
1. Add a sentence to the `Install` section, after the script, that states to follow the steps in the console output.
1. Add a note to the `Start Dev Proxy` section which states "If you get this error and you've just installed proxy, make sure you've restarted your terminal session or dot sourced your profile."

**Comment by Adam-it** [comment]
I would go with either option 2 or 3.
The info in the console is good enough for me, although I did miss it the first time 😜😂.
Thanks @garrytrinder for your response and awesome work. You rock 🤩

**Comment by garrytrinder** [comment]
PR raised https://github.com/MicrosoftDocs/microsoft-cloud-pr/pull/133
