### ISSUE TITLE
Research the implementation of behaviors

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/dev-proxy#52]
Right now we support throttling using a failure rate: customers specify the rate (likelihood) to fail each requests and if the random value we get matches the rate, we fail the request. While this is convenient for easily testing apps against specific issues, it's not representative of how Microsoft Graph behaves in practice. We should look for ways to implement behaviors, so that customers can configure the proxy either to fail requests like it does now, or follow the realistic limitations as defined at https://learn.microsoft.com/en-us/graph/throttling-limits.

**Comment by gavinbarron** [comment]
More realistic behaviors around throttling are a good idea. I am a little hesitant to have this when the proxy is not providing mock responses due to the fact that this encourages placing artificial load on the service to test these scenarios.

Given that most throttling limits are per-app and/or per-tenant in the case of interactive applications even a low volume user can be subjected to throttling behaviors with sufficient users within the app or tenant. This is an area where we will need to spend some time designing how these behaviors will work.

Another element here to consider is that prior to sending a 429 or 503 the responses have likely been delayed.

**Comment by waldekmastykarz** [comment]
> I am a little hesitant to have this when the proxy is not providing mock responses due to the fact that this encourages placing artificial load on the service to test these scenarios.

You're bringing up a very good point. What if we'd say that behaviors always have to come with mocked responses and we don't pass through any requests, so that we can truly allow testing at scale without stressing the service?

Another thing that I just realized: for delegated apps, load stems from the number of concurrent users. What if we'd allow users to specify how many users they want to test their app with? We'd use the number to divide the counters, eg. let's say we've got a limit of 1000 calls in a unit of time. If you're testing your app with 100 concurrent users, that counter becomes 10 calls in a unit of time. Of course we're making here an assumption of equal load across the different users, which wouldn't necessary always be the case, but which gives some idea of how the scale would affect the thresholds.

**Comment by gavinbarron** [comment]
> Another thing that I just realized: for delegated apps, load stems from the number of concurrent users. What if we'd allow users to specify how many users they want to test their app with? We'd use the number to divide the counters, eg. let's say we've got a limit of 1000 calls in a unit of time. If you're testing your app with 100 concurrent users, that counter becomes 10 calls in a unit of time. Of course we're making here an assumption of equal load across the different users, which wouldn't necessary always be the case, but which gives some idea of how the scale would affect the thresholds.

I like that idea. It's a massive simplification of the problem, but it serves to illustrate the point well.
