### ISSUE TITLE
Refresh PATH after Windows installation

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/dev-proxy#676]
winget doesn't support refreshing the current session when updating PATH after installation, so when `Microsoft.DevProxy` package is installed, users must start a new session to use the `devproxy` alias, if they try to run proxy an error will be thrown that `devproxy` cannot be found, this is also the same for `Microsoft.DevProxy.Beta` packages and `devproxy-beta` alias. 

We should investigate into ways that we can handle this for the user so they can use proxy immediately after install.

**Comment by waldekmastykarz** [comment]
It seems like a [known issue with winget](https://github.com/microsoft/winget-cli/issues/222) that many folks struggle with. There are some [workarounds](https://github.com/jazzdelightsme/WingetPathUpdater/blob/main/ReadMe.md). Since it's not specific to us, I suggest that we document it but don't try to fix it ourselves and rather align with winget.

**Comment by waldekmastykarz** [comment]
After exploring a couple of options, we haven't found a way that's working and automatically registers the new path with the current terminal session. As such, I suggest we document the current behavior and close this issue.

**Comment by garrytrinder** [comment]
A remark has been added to docs.

![image](https://github.com/microsoft/dev-proxy/assets/11563347/af99e9b0-9138-4f31-b203-122584d6ccbb)
