### ISSUE TITLE
The Proxy should detect `beta` calls and suggest moving to `v1.0` calls

### ISSUE THREAD

**Issue by sebastienlevert** [microsoft/dev-proxy#75]
If a `v1.0` endpoint is available, any `beta` call should get a suggestion to move to the production endpoint.

## Proposal

Identify the list of available endpoints on `v1.0` and if it matches, suggest to move.

**Comment by garrytrinder** [comment]
Great suggestion @sebastienlevert

**Comment by lballaire** [comment]
I've done something very similar about two years ago for our products and it's quite tricky even though it seems simple at first. You cannot simply look for availability of the endpoint in `v1.0`.

Some suggested specs : 
- Validate properties that are in [query parameters](https://learn.microsoft.com/en-us/graph/query-parameters?view=graph-rest-1.0&tabs=http#odata-system-query-options) such as `$expand`, `$filter`, `$orderBy`, `$search` or `$select`. It is possible that they are only available on `beta`.
  - Ex : `createdByAppId` [property](https://learn.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta#properties) for Groups
- Validate that the permissions are available, there are sometimes some permissions that are only available on `beta` for backwards compatibility purposes.
  - Ex : `Groups.Read.All` and `Groups.ReadWrite.All` to [list channel messages](https://learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=http#permissions)

The implementation I ended up doing back then was the simplest I had in mind. The idea was to intercept the call to `beta` and try it on `v1.0`. If the call worked, then I suggested to move to `v1.0`. If it failed, I would continue with the `beta` call.

However, there are still some edge cases that might arise with this and I would potentially advise against this approach especially for operations that write since the behavior might differ between versions.

**Comment by waldekmastykarz** [comment]
Thanks for sharing your experience, @lballaire, this is very helpful. You're bringing up a very good point that we can't just look at the URL, but should consider other aspect of the request, such as its parameters and data shape. This makes is tricky, because if you don't include `$select` on the request, but in your code assume that a certain property is there, which isn't on v1.0, then our suggestion for you to use v1.0 would send you down the wrong path.

As for permissions, how could we infer in a reliable way the difference between: I'm using this permission because it's the one that makes sense for my app vs. I'm using this permission because it's the only one I can use?

**Comment by lballaire** [comment]
I guess it really depends on what are the expectations towards the recommendation. I see multiple points of view in relation to `beta` to `v1.0`. Is the goal aiming at : 
- You should be able to upgrade your call as-is
- You should be able to upgrade your call if you apply all of the following changes

In the second scenario, this is where it gets interesting of course since you can give a more thorough guidance like : 

> You could upgrade, but you need to add permission P and you should be able to remove permission Q in exchange. You also should use a $select statement to ensure that your application doesn't break later down the line with this recommendation.


**My two cents**
To keep it simple, I feel like the proxy should probably give some priorities to certain guidance to start. For example, if the developer hasn't provided a `$select` parameter, well you should first start with this before we can give you a recommendation on your use of `beta`. I feel like it's more of a process instead of actually being many recommendations all at once. 

Otherwise, there is a risk that some guidance will need to duplicate logic and efforts relating to other concerns that could be isolated or encounter a risk of being erroneous. It might become very difficult to develop plugins over time if they need to be aware of all potential edge cases arising from other guidance plugins.

**Comment by waldekmastykarz** [comment]
What if we'd approach it differently? What if we offered a separate plugin that you can turn on and which would rewrite beta URLs to v1.0? Then, you can use whatever mechanism you prefer (manual or automated tests) to verify that everything in your apps still works as intended. This would help you avoid manual fiddling with your code and if you've got automated tests it would be a quick way to check which requests you can update. How does that sound?

**Comment by lballaire** [comment]
If I'm understanding this correctly, you are suggesting just to rewrite the URL without any fallback and fail if the call doesn't work on `v1.0`?

It works for automated tests that are focused on a single API call, but it could cause some issues if multiple `beta` calls are part of a same process or flow since you would most likely crash on the first call.

That was the benefit of doing a fallback on the initial beta call since it allows the flow to continue while still logging or noting the failure. I guess that could be a configuration too where you specify to stop on failure or not.

**Comment by waldekmastykarz** [comment]
Seems like to make it useful, it requires more complexity than simply comparing the URLs. We won't be working on this at the moment but can always revisit in the future. Thanks for chiming in folks!
